# Importando librerias

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

Se valida que tensorflow este instalado

In [3]:
tf.__version__

'2.10.1'

# Parte 1 - Preprosesando los datos

## Importar el dataset

In [74]:
dataset = pd.read_csv('filtered-dataset.csv')
# Solo se toman las columnas de la 7ma en adelante
X = dataset.iloc[:,7:-2].values
y = dataset.iloc[:,-2].values

In [15]:
print(X)

[['504090_AI_P0 Pull up FB' ' V' 4.1 4.5 3.828273058]
 ['504090_AI_P0 Pull up FB' ' V' 4.1 4.5 3.940582037]
 ['504090_AI_P0 Pull up FB' ' V' 4.1 4.5 3.940582037]
 ...
 ['509860_AI_RP2 On' ' Dec' 2147.0 2297.0 0.0]
 ['530740_Fuel_Pump_Relay_Ctrl_Ckt Vo' ' V' 0.0 1.0 13.49022865]
 ['530740_Fuel_Pump_Relay_Ctrl_Ckt Vo' ' V' 0.0 1.0 13.47603035]]


In [7]:
print(y)

['IC101' 'IC101' 'IC101' ... 'T1201-R1208' 'T4101 Z1003 C2901 C1702'
 'T4101 Z1003 C2901 C1702']


## Codificar data categorica (texto)

In [75]:
# from sklearn.preprocessing import LabelEncoder
# le = LabelEncoder()
# # Se codifica el nombre de la prueba
# X[:,0] = le.fit_transform(X[:,0])
# # Se codifica la unidad de medicion
# X[:,1] = le.fit_transform(X[:,1])

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [-4])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [76]:
print(X[:,-4])

[0.0 0.0 0.0 ... 0.0 0.0 0.0]


## Dividir el dataset entre el training set y el test set

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## Escalamiento de los datos

In [78]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

[[0.0 0.0 0.0 ... 1.0 1.0 0.0]
 [0.0 0.0 0.0 ... 3900.0 4100.0 0.0]
 [0.0 0.0 0.0 ... 0.0 0.0 1.0]
 ...
 [0.0 0.0 0.0 ... 1.0 1.0 0.0]
 [0.0 0.0 0.0 ... 0.5 2.0 0.004671963]
 [0.0 0.0 0.0 ... 0.0 0.0 4.0]]
